SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- DemoData INSERT
DROP PROCEDURE IF EXISTS dbo.sp_DemoData_Insert;
GO
CREATE PROCEDURE dbo.sp_DemoData_Insert
    @PLACE_HOLDER    NVARCHAR(50),
    @STATUS          TINYINT,
    @LCID            INT,
    @DEFAULT_LCID    INT,
    @ACTOR_USER_ID   INT,
    @ACTOR_SCOPE_ID  INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET QUOTED_IDENTIFIER ON;

    INSERT INTO dbo.tblDemoData (PLACE_HOLDER, STATUS, LCID, DEFAULT_LCID, OWNER_SCOPE_ID,
        CREATOR_USER_ID, CREATOR_SCOPE_ID, EDITOR_USER_ID, EDITOR_SCOPE_ID)
    VALUES (@PLACE_HOLDER, @STATUS, @LCID, @DEFAULT_LCID, @ACTOR_SCOPE_ID,
        @ACTOR_USER_ID, @ACTOR_SCOPE_ID, @ACTOR_USER_ID, @ACTOR_SCOPE_ID);

    SELECT SCOPE_IDENTITY() AS NEW_ID;
END;
GO

-- DemoData UPDATE
DROP PROCEDURE IF EXISTS dbo.sp_DemoData_Update;
GO
CREATE PROCEDURE dbo.sp_DemoData_Update
    @DEMODATA_ID     INT,
    @PLACE_HOLDER    NVARCHAR(50),
    @STATUS          TINYINT,
    @LCID            INT,
    @DEFAULT_LCID    INT,
    @ACTOR_USER_ID   INT,
    @ACTOR_SCOPE_ID  INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET QUOTED_IDENTIFIER ON;

    UPDATE dbo.tblDemoData
    SET PLACE_HOLDER = @PLACE_HOLDER,
        STATUS = @STATUS,
        LCID = @LCID,
        DEFAULT_LCID = @DEFAULT_LCID,
        EDITOR_USER_ID = @ACTOR_USER_ID,
        EDITOR_SCOPE_ID = @ACTOR_SCOPE_ID,
        MODIFIED_TIME = SYSUTCDATETIME()
    WHERE DEMODATA_ID = @DEMODATA_ID AND DELETED = 0;

    SELECT @@ROWCOUNT AS AFFECTED;
END;
GO

-- DemoData DELETE (soft)
DROP PROCEDURE IF EXISTS dbo.sp_DemoData_Delete;
GO
CREATE PROCEDURE dbo.sp_DemoData_Delete
    @DEMODATA_ID       INT,
    @ACTOR_USER_ID     INT,
    @ACTOR_SCOPE_ID    INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET QUOTED_IDENTIFIER ON;

    UPDATE dbo.tblDemoData
    SET DELETED = 1,
        STATUS = 0,
        DELETER_USER_ID = @ACTOR_USER_ID,
        DELETER_SCOPE_ID = @ACTOR_SCOPE_ID,
        DELETION_TIME = SYSUTCDATETIME()
    WHERE DEMODATA_ID = @DEMODATA_ID AND DELETED = 0;

    SELECT @@ROWCOUNT AS AFFECTED;
END;
GO

-- DemoData LIST — scope filtreli
-- @WORKING_SCOPE_IDS: virgülle ayrılmış scope ID listesi (boşsa tümünü getir)
DROP PROCEDURE IF EXISTS dbo.sp_DemoData_List;
GO
CREATE PROCEDURE dbo.sp_DemoData_List
    @WORKING_SCOPE_IDS NVARCHAR(MAX) = NULL,
    @PUBLIC_ONLY       BIT           = 0
AS
BEGIN
    SET NOCOUNT ON;
    SET QUOTED_IDENTIFIER ON;

    -- reach=AllScopes / guard bypass → tüm scope'lar (NULL). @PUBLIC_ONLY=1 ise yalniz IS_PUBLIC=1.
    IF @WORKING_SCOPE_IDS IS NULL
    BEGIN
        SELECT DEMODATA_ID, PLACE_HOLDER, STATUS, LCID, DEFAULT_LCID, OWNER_SCOPE_ID,
               CREATOR_USER_ID, CREATOR_SCOPE_ID, CREATION_TIME,
               EDITOR_USER_ID, MODIFIED_TIME
        FROM dbo.tblDemoData
        WHERE DELETED = 0
          AND (@PUBLIC_ONLY = 0 OR IS_PUBLIC = 1)
        ORDER BY DEMODATA_ID;
        RETURN;
    END

    -- scope filtresi: OWNER_SCOPE_ID IN (working set) [+ public-only]
    DECLARE @sql NVARCHAR(MAX) = N'
        SELECT DEMODATA_ID, PLACE_HOLDER, STATUS, LCID, DEFAULT_LCID, OWNER_SCOPE_ID,
               CREATOR_USER_ID, CREATOR_SCOPE_ID, CREATION_TIME,
               EDITOR_USER_ID, MODIFIED_TIME
        FROM dbo.tblDemoData
        WHERE DELETED = 0
          AND OWNER_SCOPE_ID IN (' + @WORKING_SCOPE_IDS + N')
          AND (@po = 0 OR IS_PUBLIC = 1)
        ORDER BY DEMODATA_ID';

    EXEC sp_executesql @sql, N'@po BIT', @po = @PUBLIC_ONLY;
END;
GO
