SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET NOCOUNT ON;

SET IDENTITY_INSERT core.tblScope ON;

-- system reserved root_scope: SCOPE_ID = -1
IF NOT EXISTS (SELECT 1 FROM core.tblScope WHERE SCOPE_ID = -1)
    INSERT INTO core.tblScope (SCOPE_ID, SCOPE_TYPE, STATUS, CREATOR_USER_ID, CREATOR_SCOPE_ID, EDITOR_USER_ID, EDITOR_SCOPE_ID)
    VALUES (-1, 255, 1, -1, NULL, -1, NULL);

SET IDENTITY_INSERT core.tblScope OFF;
GO

SET QUOTED_IDENTIFIER ON;
SELECT s.SCOPE_ID, s.SCOPE_TYPE, st.CODE AS SCOPE_TYPE_CODE, s.STATUS, s.CREATOR_USER_ID
FROM core.tblScope s
LEFT JOIN core.conScopeType st ON s.SCOPE_TYPE = st.SCOPE_TYPE;
GO